version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=johan
      - POSTGRES_PASSWORD=password
    ports:
      - 5439:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data